# Generated by Django 6.1 on 2026-09-02 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otptoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpToken',
        ),
    ]
