# Generated by Django 6.1 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_skills'),
        ('jobs', '0002_alter_job_guaranteed_slots_alter_job_seniority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidates', to='jobs.skill'),
        ),
    ]
