# Generated by Django 6.1 on 2026-09-14 14:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('seniority', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('guaranteed_slots', models.IntegerField()),
                ('slots_filled', models.IntegerField(default=0)),
                ('overall_min_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
                'indexes': [models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['company', '-created_at'], name='idx_jobs_company_created'), models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['status'], name='idx_jobs_status')],
                'constraints': [models.CheckConstraint(condition=models.Q(('guaranteed_slots__gt', 0)), name='chk_jobs_guaranteed_slots_positive'), models.CheckConstraint(condition=models.Q(('slots_filled__gte', 0)), name='chk_jobs_slots_filled_non_negative'), models.CheckConstraint(condition=models.Q(('slots_filled__lte', models.F('guaranteed_slots'))), name='chk_jobs_slots_not_exceeded')],
            },
        ),
    ]
