# Generated by Django 6.1 on 2026-09-15 11:11

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='guaranteed_slots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('entry level', 'Entry Level'), ('junior', 'Junior'), ('mid', 'MID'), ('senior', 'Senior')], default='junior', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='slots_filled',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.CreateModel(
            name='GuaranteeAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agreement_version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guarantee_agreements_accepted', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_agreements', to='company.company')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_agreement', to='jobs.job')),
            ],
            options={
                'db_table': 'guarantee_agreements',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='uq_skill_name_ci')],
            },
        ),
        migrations.CreateModel(
            name='JobSkillRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight_pct', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_requirements', to='jobs.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='job_requirements', to='jobs.skill')),
            ],
            options={
                'db_table': 'job_skill_requirements',
            },
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(related_name='jobs', through='jobs.JobSkillRequirement', to='jobs.skill'),
        ),
        migrations.AddIndex(
            model_name='jobskillrequirement',
            index=models.Index(fields=['job'], name='idx_job_skill_requirements_job'),
        ),
        migrations.AddConstraint(
            model_name='jobskillrequirement',
            constraint=models.UniqueConstraint(fields=('job', 'skill'), name='uq_job_skill'),
        ),
        migrations.AddConstraint(
            model_name='jobskillrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('min_score__gte', 0), ('min_score__lte', 100)), name='chk_job_skill_min_score_range'),
        ),
        migrations.AddConstraint(
            model_name='jobskillrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('weight_pct__gte', 0), ('weight_pct__lte', 100)), name='chk_job_skill_weight_pct_range'),
        ),
    ]
