# Generated by Django 6.1 on 2026-09-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_guaranteed_slots_alter_job_seniority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='guaranteed_slots',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='seniority',
            field=models.CharField(blank=True, choices=[('intern', 'Intern'), ('entry level', 'Entry Level'), ('junior', 'Junior'), ('mid', 'Mid'), ('senior', 'Senior')], default='junior', max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='slots_filled',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
